/**
 * Content Brief Schema
 *
 * Defines the structure for AI-generated content briefs based on
 * high-opportunity search queries.
 *
 * @module @workspace/shared/schemas/seo/content-brief
 */
import { z } from 'zod'

/**
 * A section heading in the content outline
 */
export const outlineSectionSchema = z.object({
    heading: z.string().describe('The H2 or H3 heading text'),
    level: z.enum(['h2', 'h3']).describe('Heading level'),
    keyPoints: z
        .array(z.string())
        .describe('Key points to cover in this section'),
})

export type OutlineSection = z.infer<typeof outlineSectionSchema>

/**
 * Complete content brief generated by AI
 */
export const contentBriefSchema = z.object({
    suggestedTitle: z
        .string()
        .describe('SEO-optimized title (50-60 characters)'),
    targetKeyword: z.string().describe('Primary keyword to target'),
    secondaryKeywords: z
        .array(z.string())
        .describe('Related keywords to include naturally'),
    targetWordCount: z
        .number()
        .int()
        .describe('Recommended word count for comprehensive coverage'),
    searchIntent: z
        .enum(['informational', 'transactional', 'navigational', 'commercial'])
        .describe('The search intent behind the query'),
    outline: z
        .array(outlineSectionSchema)
        .describe('Content outline with headings and key points'),
    introduction: z
        .string()
        .describe('Suggested introduction approach (2-3 sentences)'),
    conclusion: z
        .string()
        .describe('Suggested conclusion approach (2-3 sentences)'),
    ctaRecommendation: z
        .string()
        .describe('Recommended call-to-action for this content'),
    competitorInsights: z
        .string()
        .describe('General guidance on how to differentiate from competitors'),
    metaDescription: z
        .string()
        .describe('Suggested meta description (150-160 characters)'),
})

export type ContentBrief = z.infer<typeof contentBriefSchema>

/**
 * Input for generating a content brief
 */
export const generateContentBriefInputSchema = z.object({
    query: z.string().min(1).describe('The search query to create content for'),
    currentPosition: z
        .number()
        .optional()
        .describe('Current ranking position if known'),
    impressions: z
        .number()
        .optional()
        .describe('Monthly impressions for this query'),
})

export type GenerateContentBriefInput = z.infer<
    typeof generateContentBriefInputSchema
>
