/**
 * Keyword Ownership Registry — blog posts
 *
 * GENERATED FILE — regenerate with scripts/generate-blog-keyword-ownership.mjs
 * (see its header for the psql export command). Hand-edits are allowed for
 * cluster corrections but will be overwritten on the next regeneration, so
 * fold them into the generator's maps instead.
 *
 * Seeded from the live blog_post table on 2026-08-11:
 * every published/scheduled post appears exactly once. Posts in a known
 * duplicate cluster (plan doc §6) carry duplicateOf pointing at the
 * cluster's proposed owner. Retired slugs mirror next.config.mjs 301s so
 * ideation never re-proposes them.
 *
 * @module @workspace/shared/seo/keyword-ownership-blog.constant
 */
import type { OwnedPage } from './keyword-ownership.type'

/** All blog registry entries (live, scheduled and retired) */
export const BLOG_POST_ENTRIES: OwnedPage[] = [
    {
        url: '/how-long-to-recover-tummy-tuck',
        slug: 'how-long-to-recover-tummy-tuck',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long to recover tummy tuck',
        ownsQueries: [],
    },
    {
        url: '/what-to-wear-to-breast-reduction-surgery',
        slug: 'what-to-wear-to-breast-reduction-surgery',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what to wear to breast reduction surgery',
        ownsQueries: [],
    },
    {
        url: '/what-is-the-difference-between-tummy-tuck-and-liposuction',
        slug: 'what-is-the-difference-between-tummy-tuck-and-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword:
            'what is the difference between tummy tuck and liposuction',
        ownsQueries: [],
        duplicateOf: '/blog/tummy-tuck-vs-liposuction',
        notes: 'Legacy root URL may hold rankings — GSC evidence required before any 301.',
    },
    {
        url: '/when-can-i-sleep-without-a-bra-after-breast-reduction',
        slug: 'when-can-i-sleep-without-a-bra-after-breast-reduction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when can i sleep without a bra after breast reduction',
        ownsQueries: [],
    },
    {
        url: '/what-is-j-plasma-lipo',
        slug: 'what-is-j-plasma-lipo',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what is j plasma lipo',
        ownsQueries: [],
    },
    {
        url: '/how-old-do-you-have-to-be-to-get-liposuction',
        slug: 'how-old-do-you-have-to-be-to-get-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how old do you have to be to get liposuction',
        ownsQueries: [],
    },
    {
        url: '/when-can-i-sleep-without-a-bra-after-breast-augmentation',
        slug: 'when-can-i-sleep-without-a-bra-after-breast-augmentation',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword:
            'when can i sleep without a bra after breast augmentation',
        ownsQueries: [],
    },
    {
        url: '/how-long-after-breast-augmentation-can-i-drive',
        slug: 'how-long-after-breast-augmentation-can-i-drive',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long after breast augmentation can i drive',
        ownsQueries: [],
    },
    {
        url: '/how-long-after-breast-augmentation-can-i-swim',
        slug: 'how-long-after-breast-augmentation-can-i-swim',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long after breast augmentation can i swim',
        ownsQueries: [],
    },
    {
        url: '/how-long-after-bbl-can-i-sit',
        slug: 'how-long-after-bbl-can-i-sit',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long after bbl can i sit',
        ownsQueries: [],
    },
    {
        url: '/how-to-get-rid-of-fibrosis-after-lipo',
        slug: 'how-to-get-rid-of-fibrosis-after-lipo',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to get rid of fibrosis after lipo',
        ownsQueries: [],
    },
    {
        url: '/how-long-to-recover-from-mommy-makeover',
        slug: 'how-long-to-recover-from-mommy-makeover',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long to recover from mommy makeover',
        ownsQueries: [],
        duplicateOf: '/blog/mommy-makeover-recovery-timeline-miami',
        notes: 'Legacy root URL may hold rankings — GSC evidence required before any 301.',
    },
    {
        url: '/when-can-i-sleep-on-my-side-after-breast-reduction',
        slug: 'when-can-i-sleep-on-my-side-after-breast-reduction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when can i sleep on my side after breast reduction',
        ownsQueries: [],
    },
    {
        url: '/what-is-a-double-bbl',
        slug: 'what-is-a-double-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what is a double bbl',
        ownsQueries: [],
    },
    {
        url: '/how-many-times-can-you-get-liposuction',
        slug: 'how-many-times-can-you-get-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how many times can you get liposuction',
        ownsQueries: [],
    },
    {
        url: '/how-to-reduce-swelling-after-liposuction',
        slug: 'how-to-reduce-swelling-after-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to reduce swelling after liposuction',
        ownsQueries: [],
    },
    {
        url: '/how-to-regain-sensation-after-breast-reduction',
        slug: 'how-to-regain-sensation-after-breast-reduction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to regain sensation after breast reduction',
        ownsQueries: [],
    },
    {
        url: '/when-can-i-do-push-ups-after-breast-augmentation',
        slug: 'when-can-i-do-push-ups-after-breast-augmentation',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when can i do push ups after breast augmentation',
        ownsQueries: [],
    },
    {
        url: '/when-can-i-wear-jeans-after-bbl',
        slug: 'when-can-i-wear-jeans-after-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when can i wear jeans after bbl',
        ownsQueries: [],
    },
    {
        url: '/what-to-eat-after-liposuction',
        slug: 'what-to-eat-after-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what to eat after liposuction',
        ownsQueries: [],
    },
    {
        url: '/how-to-fix-uneven-liposuction',
        slug: 'how-to-fix-uneven-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to fix uneven liposuction',
        ownsQueries: [],
    },
    {
        url: '/what-age-can-you-get-a-bbl',
        slug: 'what-age-can-you-get-a-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what age can you get a bbl',
        ownsQueries: [],
    },
    {
        url: '/how-to-reduce-tightness-after-tummy-tuck',
        slug: 'how-to-reduce-tightness-after-tummy-tuck',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to reduce tightness after tummy tuck',
        ownsQueries: [],
    },
    {
        url: '/what-is-more-painful-bbl-or-tummy-tuck',
        slug: 'what-is-more-painful-bbl-or-tummy-tuck',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what is more painful bbl or tummy tuck',
        ownsQueries: [],
    },
    {
        url: '/how-long-after-lipo-can-i-workout',
        slug: 'how-long-after-lipo-can-i-workout',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long after lipo can i workout',
        ownsQueries: [],
    },
    {
        url: '/how-long-does-it-take-to-recover-from-chin-lipo',
        slug: 'how-long-does-it-take-to-recover-from-chin-lipo',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long does it take to recover from chin lipo',
        ownsQueries: [],
    },
    {
        url: '/how-to-fix-dents-after-bbl',
        slug: 'how-to-fix-dents-after-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to fix dents after bbl',
        ownsQueries: [],
    },
    {
        url: '/how-often-to-massage-breast-after-augmentation',
        slug: 'how-often-to-massage-breast-after-augmentation',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how often to massage breast after augmentation',
        ownsQueries: [],
    },
    {
        url: '/how-to-maintain-liposuction-results',
        slug: 'how-to-maintain-liposuction-results',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to maintain liposuction results',
        ownsQueries: [],
    },
    {
        url: '/how-long-to-quit-smoking-before-breast-reduction',
        slug: 'how-long-to-quit-smoking-before-breast-reduction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long to quit smoking before breast reduction',
        ownsQueries: [],
    },
    {
        url: '/how-to-reduce-pubic-swelling-after-tummy-tuck',
        slug: 'how-to-reduce-pubic-swelling-after-tummy-tuck',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to reduce pubic swelling after tummy tuck',
        ownsQueries: [],
    },
    {
        url: '/how-many-massages-after-lipo-360',
        slug: 'how-many-massages-after-lipo-360',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how many massages after lipo 360',
        ownsQueries: [],
    },
    {
        url: '/when-to-start-lymphatic-massage-after-lipo',
        slug: 'when-to-start-lymphatic-massage-after-lipo',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when to start lymphatic massage after lipo',
        ownsQueries: [],
    },
    {
        url: '/how-many-massages-after-bbl',
        slug: 'how-many-massages-after-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how many massages after bbl',
        ownsQueries: [],
    },
    {
        url: '/how-to-sleep-after-liposuction',
        slug: 'how-to-sleep-after-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to sleep after liposuction',
        ownsQueries: [],
    },
    {
        url: '/what-areas-does-lipo-360-cover',
        slug: 'what-areas-does-lipo-360-cover',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what areas does lipo 360 cover',
        ownsQueries: [],
    },
    {
        url: '/what-is-a-tummy-tuck-without-muscle-repair-called',
        slug: 'what-is-a-tummy-tuck-without-muscle-repair-called',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what is a tummy tuck without muscle repair called',
        ownsQueries: [],
    },
    {
        url: '/how-to-feed-the-fat-after-bbl',
        slug: 'how-to-feed-the-fat-after-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to feed the fat after bbl',
        ownsQueries: [],
    },
    {
        url: '/how-long-after-mommy-makeover-can-i-drive',
        slug: 'how-long-after-mommy-makeover-can-i-drive',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long after mommy makeover can i drive',
        ownsQueries: [],
    },
    {
        url: '/when-can-i-sleep-on-my-side-after-breast-augmentation',
        slug: 'when-can-i-sleep-on-my-side-after-breast-augmentation',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when can i sleep on my side after breast augmentation',
        ownsQueries: [],
    },
    {
        url: '/how-to-get-rid-of-bruising-after-liposuction',
        slug: 'how-to-get-rid-of-bruising-after-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to get rid of bruising after liposuction',
        ownsQueries: [],
    },
    {
        url: '/when-do-breast-augmentation-stitches-dissolve',
        slug: 'when-do-breast-augmentation-stitches-dissolve',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'when do breast augmentation stitches dissolve',
        ownsQueries: [],
    },
    {
        url: '/how-to-reduce-itching-after-lipo',
        slug: 'how-to-reduce-itching-after-lipo',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to reduce itching after lipo',
        ownsQueries: [],
    },
    {
        url: '/what-is-lipo-foam',
        slug: 'what-is-lipo-foam',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'what is lipo foam',
        ownsQueries: [],
    },
    {
        url: '/how-to-sleep-after-bbl',
        slug: 'how-to-sleep-after-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how to sleep after bbl',
        ownsQueries: [],
    },
    {
        url: '/weeks-post-op-breast-augmentation-what-to-expect',
        slug: 'weeks-post-op-breast-augmentation-what-to-expect',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'weeks post op breast augmentation what to expect',
        ownsQueries: [],
    },
    {
        url: '/how-long-to-recover-from-bbl',
        slug: 'how-long-to-recover-from-bbl',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'how long to recover from bbl',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-recovery-time-miami',
        notes: 'Legacy root URL may hold rankings — GSC evidence required before any 301.',
    },
    {
        url: '/why-do-bbl-stink',
        slug: 'why-do-bbl-stink',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'why do bbl stink',
        ownsQueries: [],
    },
    {
        url: '/how-to-choose-the-best-plastic-surgeon-in-miami-10-things-to-look-for',
        slug: 'how-to-choose-the-best-plastic-surgeon-in-miami-10-things-to-look-for',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword:
            'how to choose the best plastic surgeon in miami 10 things to look for',
        ownsQueries: [],
    },
    {
        url: '/blog/affordable-plastic-surgery-miami',
        slug: 'affordable-plastic-surgery-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'affordable plastic surgery miami',
        ownsQueries: [],
        duplicateOf: '/plastic-surgery-cost-miami',
    },
    {
        url: '/blog/bbl-recovery-miami-moms-guide',
        slug: 'bbl-recovery-miami-moms-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl recovery miami moms guide',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-recovery-time-miami',
    },
    {
        url: '/blog/liposuction-miami-moms-tips',
        slug: 'liposuction-miami-moms-tips',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction miami moms tips',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-vs-butt-implants-miami',
        slug: 'bbl-vs-butt-implants-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl vs butt implants miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-miami-recovery-faq',
        slug: 'bbl-miami-recovery-faq',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl miami recovery faq',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-recovery-time-miami',
    },
    {
        url: '/blog/breast-lift-miami-quiz',
        slug: 'breast-lift-miami-quiz',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift miami quiz',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-miami-candidate-checklist',
        slug: 'tummy-tuck-miami-candidate-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck miami candidate checklist',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-vs-reduction-miami',
        slug: 'breast-lift-vs-reduction-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift vs reduction miami',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-recovery-time-miami',
        slug: 'tummy-tuck-recovery-time-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck recovery time miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-vs-breast-lift',
        slug: 'breast-augmentation-vs-breast-lift',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation vs breast lift',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-miami-recovery-guide',
        slug: 'facelift-miami-recovery-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift miami recovery guide',
        ownsQueries: [],
    },
    {
        url: '/blog/best-facelift-age-miami',
        slug: 'best-facelift-age-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best facelift age miami',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-myths-debunked',
        slug: 'facelift-myths-debunked',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift myths debunked',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-myths-miami-moms',
        slug: 'tummy-tuck-myths-miami-moms',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck myths miami moms',
        ownsQueries: [],
    },
    {
        url: '/blog/liposuction-miami-post-pregnancy-guide',
        slug: 'liposuction-miami-post-pregnancy-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction miami post pregnancy guide',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-candidate-miami',
        slug: 'breast-reduction-candidate-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction candidate miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-miami-post-pregnancy',
        slug: 'breast-lift-miami-post-pregnancy',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift miami post pregnancy',
        ownsQueries: [],
    },
    {
        url: '/blog/mommy-makeover-recovery-miami',
        slug: 'mommy-makeover-recovery-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover recovery miami',
        ownsQueries: [],
        duplicateOf: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/blog/mommy-makeover-miami-candidate-checklist',
        slug: 'mommy-makeover-miami-candidate-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover miami candidate checklist',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-implants-miami',
        slug: 'breast-lift-implants-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift implants miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-miami-post-pregnancy-quiz',
        slug: 'bbl-miami-post-pregnancy-quiz',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl miami post pregnancy quiz',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-miami-post-pregnancy-guide',
    },
    {
        url: '/blog/blepharoplasty-facelift-miami',
        slug: 'blepharoplasty-facelift-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'blepharoplasty facelift miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-before-after-miami',
        slug: 'breast-augmentation-before-after-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation before after miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-before-after-miami-mom',
        slug: 'bbl-before-after-miami-mom',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl before after miami mom',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-miami-post-pregnancy-guide',
    },
    {
        url: '/blog/board-certified-plastic-surgeon-miami',
        slug: 'board-certified-plastic-surgeon-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'board certified plastic surgeon miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-candidate-quiz',
        slug: 'breast-augmentation-candidate-quiz',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation candidate quiz',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-vs-liposuction',
        slug: 'tummy-tuck-vs-liposuction',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck vs liposuction',
        ownsQueries: [],
    },
    {
        url: '/blog/blepharoplasty-candidate-miami-checklist',
        slug: 'blepharoplasty-candidate-miami-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'blepharoplasty candidate miami checklist',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-recovery-miami',
        slug: 'breast-augmentation-recovery-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation recovery miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-recovery-miami',
        slug: 'breast-reduction-recovery-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction recovery miami',
        ownsQueries: [],
    },
    {
        url: '/blog/blepharoplasty-myths-busted',
        slug: 'blepharoplasty-myths-busted',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'blepharoplasty myths busted',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-recovery-time-miami',
        slug: 'facelift-recovery-time-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift recovery time miami',
        ownsQueries: [],
    },
    {
        url: '/blog/liposuction-candidate-miami',
        slug: 'liposuction-candidate-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction candidate miami',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-vs-blepharoplasty-miami',
        slug: 'facelift-vs-blepharoplasty-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift vs blepharoplasty miami',
        ownsQueries: [],
    },
    {
        url: '/blog/best-blepharoplasty-age-miami-checklist',
        slug: 'best-blepharoplasty-age-miami-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best blepharoplasty age miami checklist',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-recovery-guide-miami',
        slug: 'breast-lift-recovery-guide-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift recovery guide miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-miami-mom-tips',
        slug: 'breast-reduction-miami-mom-tips',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction miami mom tips',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-prep-miami',
        slug: 'breast-lift-prep-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift prep miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-miami-results-timeline',
        slug: 'bbl-miami-results-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl miami results timeline',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-vs-bbl-miami',
        slug: 'tummy-tuck-vs-bbl-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck vs bbl miami',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-scars-miami',
        slug: 'facelift-scars-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift scars miami',
        ownsQueries: [],
    },
    {
        url: '/blog/best-age-breast-augmentation-miami',
        slug: 'best-age-breast-augmentation-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best age breast augmentation miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-myths-busted',
        slug: 'breast-lift-myths-busted',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift myths busted',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-miami-post-pregnancy-guide',
        slug: 'bbl-miami-post-pregnancy-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl miami post pregnancy guide',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-results-miami',
        slug: 'breast-reduction-results-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction results miami',
        ownsQueries: [],
    },
    {
        url: '/blog/best-age-breast-lift-miami',
        slug: 'best-age-breast-lift-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best age breast lift miami',
        ownsQueries: [],
    },
    {
        url: '/blog/liposuction-vs-bbl-miami',
        slug: 'liposuction-vs-bbl-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction vs bbl miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-scars-miami-timeline',
        slug: 'breast-augmentation-scars-miami-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation scars miami timeline',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-diastasis-recti-miami',
        slug: 'tummy-tuck-diastasis-recti-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck diastasis recti miami',
        ownsQueries: [],
    },
    {
        url: '/blog/prepare-blepharoplasty-miami',
        slug: 'prepare-blepharoplasty-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'prepare blepharoplasty miami',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-recovery-ozempic-miami',
        slug: 'tummy-tuck-recovery-ozempic-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck recovery ozempic miami',
        ownsQueries: [],
    },
    {
        url: '/blog/safe-plastic-surgery-miami',
        slug: 'safe-plastic-surgery-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'safe plastic surgery miami',
        ownsQueries: [],
    },
    {
        url: '/blog/best-age-breast-reduction-miami',
        slug: 'best-age-breast-reduction-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best age breast reduction miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-scars-miami',
        slug: 'breast-reduction-scars-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction scars miami',
        ownsQueries: [],
    },
    {
        url: '/blog/choose-plastic-surgeons-miami',
        slug: 'choose-plastic-surgeons-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'choose plastic surgeons miami',
        ownsQueries: [],
        duplicateOf:
            '/how-to-choose-the-best-plastic-surgeon-in-miami-10-things-to-look-for',
    },
    {
        url: '/blog/tummy-tuck-scars-miami',
        slug: 'tummy-tuck-scars-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck scars miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-candidate-checklist',
        slug: 'breast-lift-candidate-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift candidate checklist',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-miami-post-pregnancy',
        slug: 'breast-augmentation-miami-post-pregnancy',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation miami post pregnancy',
        ownsQueries: [],
    },
    {
        url: '/blog/liposuction-recovery-time-miami',
        slug: 'liposuction-recovery-time-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction recovery time miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-reduction-weight-loss-quiz',
        slug: 'breast-reduction-weight-loss-quiz',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction weight loss quiz',
        ownsQueries: [],
        duplicateOf: '/blog/breast-reduction-weight-loss-miami',
    },
    {
        url: '/blog/liposuction-vs-breast-augmentation-miami',
        slug: 'liposuction-vs-breast-augmentation-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction vs breast augmentation miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-scars-miami',
        slug: 'breast-lift-scars-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift scars miami',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-mommy-makeover-miami',
        slug: 'tummy-tuck-mommy-makeover-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck mommy makeover miami',
        ownsQueries: [],
    },
    {
        url: '/blog/minimize-blepharoplasty-scars-miami',
        slug: 'minimize-blepharoplasty-scars-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'minimize blepharoplasty scars miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-vs-reduction-miami',
        slug: 'breast-augmentation-vs-reduction-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation vs reduction miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-miami-candidate',
        slug: 'breast-augmentation-miami-candidate',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation miami candidate',
        ownsQueries: [],
    },
    {
        url: '/blog/best-age-tummy-tuck-miami',
        slug: 'best-age-tummy-tuck-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best age tummy tuck miami',
        ownsQueries: [],
    },
    {
        url: '/blog/mommy-makeover-vs-bbl-miami',
        slug: 'mommy-makeover-vs-bbl-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover vs bbl miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-recovery-time-miami',
        slug: 'bbl-recovery-time-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl recovery time miami',
        ownsQueries: [],
    },
    {
        url: '/blog/blepharoplasty-questions-miami',
        slug: 'blepharoplasty-questions-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'blepharoplasty questions miami',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-results-longevity-miami',
        slug: 'facelift-results-longevity-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift results longevity miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-aug-vs-bbl-miami-moms',
        slug: 'breast-aug-vs-bbl-miami-moms',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast aug vs bbl miami moms',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-myths-miami-moms',
        slug: 'bbl-myths-miami-moms',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl myths miami moms',
        ownsQueries: [],
    },
    {
        url: '/blog/liposuction-recovery-ozempic-miami',
        slug: 'liposuction-recovery-ozempic-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'liposuction recovery ozempic miami',
        ownsQueries: [],
    },
    {
        url: '/blog/miami-bbl-recovery-guide',
        slug: 'miami-bbl-recovery-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'miami bbl recovery guide',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-recovery-time-miami',
    },
    {
        url: '/blog/mommy-makeover-compression-garments-guide',
        slug: 'mommy-makeover-compression-garments-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover compression garments guide',
        ownsQueries: [],
    },
    {
        url: '/blog/mommy-makeover-questions-miami',
        slug: 'mommy-makeover-questions-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover questions miami',
        ownsQueries: [],
    },
    {
        url: '/blog/mommy-makeover-recovery-timeline-miami',
        slug: 'mommy-makeover-recovery-timeline-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover recovery timeline miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-safety-miami',
        slug: 'breast-augmentation-safety-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation safety miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-weight-loss-miami',
        slug: 'breast-augmentation-weight-loss-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation weight loss miami',
        ownsQueries: [],
    },
    {
        url: '/blog/combine-bbl-tummy-tuck-miami',
        slug: 'combine-bbl-tummy-tuck-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'combine bbl tummy tuck miami',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-safety-miami',
        slug: 'bbl-safety-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl safety miami',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-recovery-tips-miami',
        slug: 'breast-augmentation-recovery-tips-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation recovery tips miami',
        ownsQueries: [],
    },
    {
        url: '/blog/best-board-certified-plastic-surgeons-miami',
        slug: 'best-board-certified-plastic-surgeons-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'best board certified plastic surgeons miami',
        ownsQueries: [],
        duplicateOf: '/blog/board-certified-plastic-surgeon-miami',
    },
    {
        url: '/blog/breast-reduction-exercise-timeline-miami',
        slug: 'breast-reduction-exercise-timeline-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction exercise timeline miami',
        ownsQueries: [],
    },
    {
        url: '/blog/facelift-results-miami-tips',
        slug: 'facelift-results-miami-tips',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'facelift results miami tips',
        ownsQueries: [],
        duplicateOf: '/blog/facelift-results-longevity-miami',
    },
    {
        url: '/blog/breast-augmentation-recovery-exercises',
        slug: 'breast-augmentation-recovery-exercises',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation recovery exercises',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-lift-recovery-weight-loss-miami',
        slug: 'breast-lift-recovery-weight-loss-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast lift recovery weight loss miami',
        ownsQueries: [],
    },
    {
        url: '/blog/mini-tummy-tuck-miami-recovery',
        slug: 'mini-tummy-tuck-miami-recovery',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mini tummy tuck miami recovery',
        ownsQueries: [],
    },
    {
        url: '/blog/tummy-tuck-recovery-myths-miami-moms',
        slug: 'tummy-tuck-recovery-myths-miami-moms',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck recovery myths miami moms',
        ownsQueries: [],
        duplicateOf: '/blog/tummy-tuck-myths-miami-moms',
    },
    {
        url: '/blog/breast-reduction-weight-loss-miami',
        slug: 'breast-reduction-weight-loss-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast reduction weight loss miami',
        ownsQueries: [],
    },
    {
        url: '/blog/ozempic-tummy-tuck-myths-miami',
        slug: 'ozempic-tummy-tuck-myths-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'ozempic tummy tuck myths miami',
        ownsQueries: [],
        duplicateOf: '/blog/tummy-tuck-recovery-ozempic-miami',
    },
    {
        url: '/blog/exercises-after-bbl-timeline',
        slug: 'exercises-after-bbl-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'exercises after bbl timeline',
        ownsQueries: [],
    },
    {
        url: '/blog/bbl-recovery-mistakes-miami',
        slug: 'bbl-recovery-mistakes-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl recovery mistakes miami',
        ownsQueries: [],
        duplicateOf: '/blog/bbl-recovery-time-miami',
    },
    {
        url: '/blog/mommy-makeover-recovery-signs',
        slug: 'mommy-makeover-recovery-signs',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover recovery signs',
        ownsQueries: [],
        duplicateOf: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/blog/bbl-compression-garment-timeline',
        slug: 'bbl-compression-garment-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'bbl compression garment timeline',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-augmentation-pain-management',
        slug: 'breast-augmentation-pain-management',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation pain management',
        ownsQueries: [],
    },
    {
        url: '/blog/mommy-makeover-recovery-exercises',
        slug: 'mommy-makeover-recovery-exercises',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'mommy makeover recovery exercises',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-implants-drop-fluff-timeline',
        slug: 'breast-implants-drop-fluff-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast implants drop fluff timeline',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-implant-size-guide',
        slug: 'breast-implant-size-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast implant size guide',
        ownsQueries: [],
    },
    {
        url: '/blog/breast-implant-illness-symptoms',
        slug: 'breast-implant-illness-symptoms',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast implant illness symptoms',
        ownsQueries: [],
    },
    {
        url: '/blog/exercises-after-tummy-tuck-miami',
        slug: 'exercises-after-tummy-tuck-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'exercises after tummy tuck miami',
        ownsQueries: [],
    },
    {
        url: '/blog/flying-after-bbl-tips',
        slug: 'flying-after-bbl-tips',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'flying after bbl tips',
        ownsQueries: [],
    },
    {
        url: '/blog/when-can-you-work-out-after-breast-augmentation',
        slug: 'when-can-you-work-out-after-breast-augmentation',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'exercise after breast augmentation',
        ownsQueries: ['when can you work out after breast augmentation'],
    },
    {
        url: '/blog/swelling-and-asymmetry-after-breast-augmentation-faq',
        slug: 'swelling-and-asymmetry-after-breast-augmentation-faq',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'breast augmentation swelling asymmetry',
        ownsQueries: ['swelling and asymmetry after breast augmentation faq'],
        notes: 'Scheduled, not yet published.',
    },
    {
        url: '/blog/5-weeks-post-op-breast-augmentation-what-s-normal',
        slug: '5-weeks-post-op-breast-augmentation-what-s-normal',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: '5 weeks post op breast augmentation',
        ownsQueries: ['5 weeks post op breast augmentation what s normal'],
        notes: 'Scheduled, not yet published.',
    },
    {
        url: '/blog/tummy-tuck-drains-what-they-are-how-long-they-stay',
        slug: 'tummy-tuck-drains-what-they-are-how-long-they-stay',
        kind: 'blog',
        intent: 'informational',
        status: 'live',
        primaryKeyword: 'tummy tuck drains',
        ownsQueries: ['tummy tuck drains what they are how long they stay'],
        notes: 'Scheduled, not yet published.',
    },
    {
        url: '/mommy-makeover-miami-guide',
        slug: 'mommy-makeover-miami-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover miami guide',
        ownsQueries: [],
        redirectsTo: '/procedures/mommy-makeover-miami',
    },
    {
        url: '/prepare-mommy-makeover-miami',
        slug: 'prepare-mommy-makeover-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'prepare mommy makeover miami',
        ownsQueries: [],
        redirectsTo: '/procedures/mommy-makeover-miami',
    },
    {
        url: '/mommy-makeover-myths-miami',
        slug: 'mommy-makeover-myths-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover myths miami',
        ownsQueries: [],
        redirectsTo: '/procedures/mommy-makeover-miami',
    },
    {
        url: '/mommy-makeover-recovery-timeline',
        slug: 'mommy-makeover-recovery-timeline',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover recovery timeline',
        ownsQueries: [],
        redirectsTo: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/mommy-makeover-recovery-guide',
        slug: 'mommy-makeover-recovery-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover recovery guide',
        ownsQueries: [],
        redirectsTo: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/mommy-makeover-recovery-time-miami',
        slug: 'mommy-makeover-recovery-time-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover recovery time miami',
        ownsQueries: [],
        redirectsTo: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/mommy-makeover-recovery-pain-management',
        slug: 'mommy-makeover-recovery-pain-management',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover recovery pain management',
        ownsQueries: [],
        redirectsTo: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/mommy-makeover-recovery-pain-guide',
        slug: 'mommy-makeover-recovery-pain-guide',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'mommy makeover recovery pain guide',
        ownsQueries: [],
        redirectsTo: '/blog/mommy-makeover-recovery-timeline-miami',
    },
    {
        url: '/miami-liposuction-cost',
        slug: 'miami-liposuction-cost',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'miami liposuction cost',
        ownsQueries: [],
        redirectsTo: '/blog/liposuction-cost-miami',
    },
    {
        url: '/blepharoplasty-candidate-checklist',
        slug: 'blepharoplasty-candidate-checklist',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'blepharoplasty candidate checklist',
        ownsQueries: [],
        redirectsTo: '/blog/blepharoplasty-candidate-miami-checklist',
    },
    {
        url: '/blepharoplasty-miami-candidate',
        slug: 'blepharoplasty-miami-candidate',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'blepharoplasty miami candidate',
        ownsQueries: [],
        redirectsTo: '/blog/blepharoplasty-candidate-miami-checklist',
    },
    {
        url: '/best-blepharoplasty-age-miami',
        slug: 'best-blepharoplasty-age-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'best blepharoplasty age miami',
        ownsQueries: [],
        redirectsTo: '/blog/best-blepharoplasty-age-miami-checklist',
    },
    {
        url: '/liposuction-candidate-checklist-miami',
        slug: 'liposuction-candidate-checklist-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'liposuction candidate checklist miami',
        ownsQueries: [],
        redirectsTo: '/blog/liposuction-candidate-miami',
    },
    {
        url: '/liposuction-miami-moms-faq',
        slug: 'liposuction-miami-moms-faq',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'liposuction miami moms faq',
        ownsQueries: [],
        redirectsTo: '/blog/liposuction-miami-moms-tips',
    },
    {
        url: '/breast-reduction-miami-recovery-candidates',
        slug: 'breast-reduction-miami-recovery-candidates',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'breast reduction miami recovery candidates',
        ownsQueries: [],
        redirectsTo: '/blog/breast-reduction-candidate-miami',
    },
    {
        url: '/what-is-the-mommy-makeover-procedure',
        slug: 'what-is-the-mommy-makeover-procedure',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'what is the mommy makeover procedure',
        ownsQueries: [],
        redirectsTo: '/procedures/mommy-makeover-miami',
    },
    {
        url: '/breast-reduction-cost-miami',
        slug: 'breast-reduction-cost-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'breast reduction cost miami',
        ownsQueries: [],
        redirectsTo: '/procedures/breast-reduction-miami',
    },
    {
        url: '/miami-breast-reduction-cost-weight-loss',
        slug: 'miami-breast-reduction-cost-weight-loss',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'miami breast reduction cost weight loss',
        ownsQueries: [],
        redirectsTo: '/procedures/breast-reduction-miami',
    },
    {
        url: '/facelift-cost-miami',
        slug: 'facelift-cost-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'facelift cost miami',
        ownsQueries: [],
        redirectsTo: '/procedures/facelift-miami',
    },
    {
        url: '/breast-reduction-surgeons-miami',
        slug: 'breast-reduction-surgeons-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'breast reduction surgeons miami',
        ownsQueries: [],
        redirectsTo: '/procedures/breast-reduction-miami',
    },
    {
        url: '/best-breast-lift-surgeons-miami',
        slug: 'best-breast-lift-surgeons-miami',
        kind: 'blog',
        intent: 'informational',
        status: 'retired',
        primaryKeyword: 'best breast lift surgeons miami',
        ownsQueries: [],
        redirectsTo: '/procedures/breast-lift-miami',
    },
]
