CREATE TABLE "beta_feedback" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"device_type" text NOT NULL,
	"device_type_other" text,
	"browser_type" text NOT NULL,
	"browser_type_other" text,
	"overall_design_rating" integer NOT NULL,
	"visual_aesthetics_rating" integer NOT NULL,
	"design_likes" text,
	"design_dislikes" text,
	"navigation_ease" text NOT NULL,
	"has_broken_links" boolean DEFAULT false,
	"broken_links_description" text,
	"wording_clarity_rating" integer NOT NULL,
	"has_typos" boolean DEFAULT false,
	"typos_description" text,
	"has_technical_issues" boolean DEFAULT false,
	"technical_issues_description" text,
	"overall_satisfaction_rating" integer NOT NULL,
	"recommendations" text,
	"wants_ux_testing" boolean DEFAULT false,
	"email" text,
	"user_agent" text,
	"ip_address" text,
	"page_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bug_report" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"page_url" text NOT NULL,
	"description" text NOT NULL,
	"steps_to_reproduce" text,
	"expected_behavior" text,
	"actual_behavior" text,
	"device_type" text,
	"browser_type" text,
	"browser_version" text,
	"screen_size" text,
	"severity" text DEFAULT 'medium',
	"status" text DEFAULT 'new',
	"reporter_email" text,
	"reporter_name" text,
	"user_agent" text,
	"ip_address" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
