/**
 * Configuration Module
 *
 * Re-exports all configuration-related types, constants, and utilities.
 */

// Export configuration types
export type {
    SEOConfig,
    DefaultMetadata,
    TwitterConfig,
    TwitterCardType,
    OpenGraphConfig,
    OpenGraphType,
    OrganizationConfig,
    RobotsConfig,
    EnvironmentConfig,
    SocialProfile,
    ContactInfo,
    ImageMetadata,
} from './seo-config.type'

// Export schema.org constants
export {
    // Context
    SCHEMA_ORG_CONTEXT,
    // Schema types
    SCHEMA_TYPE_ORGANIZATION,
    SCHEMA_TYPE_WEBSITE,
    SCHEMA_TYPE_WEBPAGE,
    SCHEMA_TYPE_ARTICLE,
    SCHEMA_TYPE_BLOG_POSTING,
    SCHEMA_TYPE_NEWS_ARTICLE,
    SCHEMA_TYPE_BREADCRUMB_LIST,
    SCHEMA_TYPE_LIST_ITEM,
    SCHEMA_TYPE_FAQ_PAGE,
    SCHEMA_TYPE_QUESTION,
    SCHEMA_TYPE_ANSWER,
    SCHEMA_TYPE_PRODUCT,
    SCHEMA_TYPE_OFFER,
    SCHEMA_TYPE_AGGREGATE_RATING,
    SCHEMA_TYPE_REVIEW,
    SCHEMA_TYPE_RATING,
    SCHEMA_TYPE_LOCAL_BUSINESS,
    SCHEMA_TYPE_POSTAL_ADDRESS,
    SCHEMA_TYPE_GEO_COORDINATES,
    SCHEMA_TYPE_CONTACT_POINT,
    SCHEMA_TYPE_PERSON,
    SCHEMA_TYPE_IMAGE_OBJECT,
    SCHEMA_TYPE_VIDEO_OBJECT,
    SCHEMA_TYPE_SEARCH_ACTION,
    // Property URLs
    SCHEMA_PROP_POTENTIAL_ACTION,
    SCHEMA_PROP_SEARCH_ACTION,
    SCHEMA_PROP_TARGET,
    SCHEMA_PROP_QUERY_INPUT,
    // Item availability
    ITEM_AVAILABILITY_IN_STOCK,
    ITEM_AVAILABILITY_OUT_OF_STOCK,
    ITEM_AVAILABILITY_PREORDER,
    ITEM_AVAILABILITY_BACKORDER,
    ITEM_AVAILABILITY_DISCONTINUED,
    ITEM_AVAILABILITY_IN_STORE_ONLY,
    ITEM_AVAILABILITY_LIMITED_AVAILABILITY,
    ITEM_AVAILABILITY_ONLINE_ONLY,
    ITEM_AVAILABILITY_SOLD_OUT,
    // Item condition
    ITEM_CONDITION_NEW,
    ITEM_CONDITION_USED,
    ITEM_CONDITION_REFURBISHED,
    ITEM_CONDITION_DAMAGED,
    // Offer item condition
    OFFER_ITEM_CONDITION_NEW,
    OFFER_ITEM_CONDITION_USED,
    OFFER_ITEM_CONDITION_REFURBISHED,
    // Business types
    BUSINESS_TYPE_RESTAURANT,
    BUSINESS_TYPE_STORE,
    BUSINESS_TYPE_HOTEL,
    BUSINESS_TYPE_MEDICAL_ORGANIZATION,
    BUSINESS_TYPE_EDUCATIONAL_ORGANIZATION,
    BUSINESS_TYPE_AUTOMOTIVE_BUSINESS,
    BUSINESS_TYPE_ENTERTAINMENT_BUSINESS,
    BUSINESS_TYPE_FINANCIAL_SERVICE,
    BUSINESS_TYPE_FOOD_ESTABLISHMENT,
    BUSINESS_TYPE_GOVERNMENT_OFFICE,
    BUSINESS_TYPE_HEALTH_AND_BEAUTY_BUSINESS,
    BUSINESS_TYPE_HOME_AND_CONSTRUCTION_BUSINESS,
    BUSINESS_TYPE_LEGAL_SERVICE,
    BUSINESS_TYPE_LIBRARY,
    BUSINESS_TYPE_LODGING_BUSINESS,
    BUSINESS_TYPE_PROFESSIONAL_SERVICE,
    BUSINESS_TYPE_SPORTS_ACTIVITY_LOCATION,
    // Contact types
    CONTACT_TYPE_CUSTOMER_SERVICE,
    CONTACT_TYPE_TECHNICAL_SUPPORT,
    CONTACT_TYPE_BILLING_SUPPORT,
    CONTACT_TYPE_SALES,
    CONTACT_TYPE_RESERVATIONS,
    CONTACT_TYPE_EMERGENCY,
    // Days of week
    DAY_MONDAY,
    DAY_TUESDAY,
    DAY_WEDNESDAY,
    DAY_THURSDAY,
    DAY_FRIDAY,
    DAY_SATURDAY,
    DAY_SUNDAY,
    // Default values
    DEFAULT_IMAGE_WIDTH,
    DEFAULT_IMAGE_HEIGHT,
    DEFAULT_LOCALE,
    DEFAULT_CURRENCY,
    // Robots meta tags
    ROBOTS_INDEX,
    ROBOTS_NOINDEX,
    ROBOTS_FOLLOW,
    ROBOTS_NOFOLLOW,
    ROBOTS_NOARCHIVE,
    ROBOTS_NOSNIPPET,
    ROBOTS_NOIMAGEINDEX,
    ROBOTS_NOTRANSLATE,
    // Twitter card types
    TWITTER_CARD_SUMMARY,
    TWITTER_CARD_SUMMARY_LARGE_IMAGE,
    TWITTER_CARD_APP,
    TWITTER_CARD_PLAYER,
    // Open Graph types
    OG_TYPE_WEBSITE,
    OG_TYPE_ARTICLE,
    OG_TYPE_BOOK,
    OG_TYPE_PROFILE,
    OG_TYPE_VIDEO_MOVIE,
    OG_TYPE_VIDEO_EPISODE,
    OG_TYPE_VIDEO_TV_SHOW,
    OG_TYPE_VIDEO_OTHER,
    OG_TYPE_MUSIC_SONG,
    OG_TYPE_MUSIC_ALBUM,
    OG_TYPE_MUSIC_PLAYLIST,
    OG_TYPE_MUSIC_RADIO_STATION,
    // Search input
    SEARCH_INPUT_ENCODING,
} from './schema-org.constant'

// Export configuration utilities
export {
    getSiteUrl,
    getSiteName,
    getSiteDescription,
    getTwitterHandle,
    getFacebookAppId,
    getEnvironment,
    shouldEnableIndexing,
    getDefaultRobotsConfig,
    getLocale,
    createDefaultSEOConfig,
    mergeSEOConfig,
} from './seo.config'
